<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
if ($APPLICATION->GetCurPage() === '/projects/') {
	$APPLICATION->SetPageProperty("body_class", "page-projects");
}
$APPLICATION->SetTitle("ТВ-проекты");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"projects", 
	array(
		"IBLOCK_TYPE" => "aspro_max_content",
		"IBLOCK_ID" => "61",
		"NEWS_COUNT" => "10",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"FILTER_NAME" => "arProjectFilter",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "DESC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/projects/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "100000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "N",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_ACTIVE_DATE_FORMAT" => "j F Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "DETAIL_TEXT",
			3 => "DETAIL_PICTURE",
			4 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "TASK_PROJECT",
			1 => "FORM_ORDER",
			2 => "FORM_QUESTION",
			3 => "LINK_GOODS",
			4 => "ORDERER",
			5 => "SITE",
			6 => "DATA",
			7 => "AUTHOR",
			8 => "LINK_BRANDS",
			9 => "LINK_VACANCY",
			10 => "KLIENT",
			11 => "LINK_LANDINGS",
			12 => "LINK_NEWS",
			13 => "LINK_REVIEWS",
			14 => "LINK_PARTNERS",
			15 => "LINK_PROJECTS",
			16 => "LINK_STAFF",
			17 => "LINK_BLOG",
			18 => "LINK_TIZERS",
			19 => "LINK_SERVICES",
			20 => "LINK_TEAM",
			21 => "LINK_COMPANY",
			22 => "FORM_PROJECT",
			23 => "DOCUMENTS",
			24 => "PHOTOS",
			25 => "GALLEY_BIG",
			26 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"IMAGE_POSITION" => "left",
		"USE_SHARE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"USE_REVIEW" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"S_ASK_QUESTION" => "",
		"S_ORDER_PROJECT" => "Заказать проект",
		"T_GALLERY" => "",
		"T_DOCS" => "",
		"T_PROJECTS" => "Похожие проекты",
		"T_CHARACTERISTICS" => "",
		"COMPONENT_TEMPLATE" => "projects",
		"SET_LAST_MODIFIED" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "Y",
		"MESSAGE_404" => "",
		"FORM_ID" => "",
		"GALLERY_TYPE" => "small",
		"T_GOODS" => "Товары",
		"T_SERVICES" => "",
		"T_REVIEWS" => "Отзыв клиента",
		"SECTION_ELEMENTS_TYPE_VIEW" => "FROM_MODULE",
		"ELEMENT_TYPE_VIEW" => "element_1",
		"LINE_ELEMENT_COUNT" => "3",
		"LINE_ELEMENT_COUNT_LIST" => "3",
		"SHOW_SECTION_PREVIEW_DESCRIPTION" => "Y",
		"SHOW_SECTION_DESCRIPTION" => "Y",
		"S_ORDER_SERVISE" => "Заказать проект",
		"SHOW_MAX_ELEMENT" => "N",
		"T_MAX_LINK" => "",
		"T_PREV_LINK" => "",
		"FORM_ID_ORDER_SERVISE" => "",
		"IMAGE_WIDE" => "Y",
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_BRAND_USE" => "Y",
		"DETAIL_BRAND_PROP_CODE" => array(
			0 => "TIZERS",
			1 => "",
		),
		"T_CLIENTS" => "",
		"STRICT_SECTION_CHECK" => "N",
		"LIST_VIEW" => "slider",
		"LINKED_ELEMENST_PAGE_COUNT" => "20",
		"SHOW_DISCOUNT_PERCENT_NUMBER" => "N",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"STORES" => array(
			0 => "",
			1 => "",
		),
		"HIDE_NOT_AVAILABLE" => "N",
		"FILE_404" => "",
		"SHOW_FILTER_DATE" => "Y",
		"SHOW_ASK_BLOCK" => "N",
		"SHOW_BORDER_ELEMENT" => "Y",
		"USE_BG_IMAGE_ALTERNATE" => "Y",
		"BG_POSITION" => "center",
		"TYPE_IMG" => "lg",
		"SIZE_IN_ROW" => "4",
		"TITLE_SHOW_FON" => "N",
		"SIDE_LEFT_BLOCK" => "FROM_MODULE",
		"TYPE_LEFT_BLOCK" => "FROM_MODULE",
		"ALL_BLOCK_BG" => "Y",
		"TYPE_HEAD_BLOCK" => "FROM_MODULE",
		"SIDE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"TYPE_LEFT_BLOCK_DETAIL" => "FROM_MODULE",
		"IBLOCK_LINK_NEWS_ID" => "66",
		"IBLOCK_LINK_SERVICES_ID" => "68",
		"IBLOCK_LINK_TIZERS_ID" => "56",
		"IBLOCK_LINK_REVIEWS_ID" => "65",
		"IBLOCK_LINK_STAFF_ID" => "62",
		"IBLOCK_LINK_VACANCY_ID" => "48",
		"IBLOCK_LINK_BLOG_ID" => "63",
		"IBLOCK_LINK_PROJECTS_ID" => "61",
		"IBLOCK_LINK_BRANDS_ID" => "76",
		"IBLOCK_LINK_LANDINGS_ID" => "",
		"BLOCK_SERVICES_NAME" => "Услуги",
		"BLOCK_NEWS_NAME" => "Новости",
		"BLOCK_TIZERS_NAME" => "",
		"BLOCK_REVIEWS_NAME" => "Отзывы",
		"BLOCK_STAFF_NAME" => "Сотрудники",
		"BLOCK_VACANCY_NAME" => "Вакансии",
		"BLOCK_PROJECTS_NAME" => "Проекты",
		"BLOCK_BRANDS_NAME" => "Бренды",
		"BLOCK_BLOG_NAME" => "Статьи",
		"BLOCK_LANDINGS_NAME" => "Коллекции",
		"STAFF_TYPE_DETAIL" => "list",
		"DETAIL_BLOCKS_ALL_ORDER" => "gallery,desc,char,tizers,docs,services,goods,reviews,news,vacancy,blog,form_order,projects,staff,brands,landings,partners,comments,video",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_BLOG_USE" => "N",
		"DETAIL_VK_USE" => "N",
		"DETAIL_FB_USE" => "N",
		"IBLOCK_LINK_PARTNERS_ID" => "",
		"BLOCK_PARTNERS_NAME" => "Партнеры",
		"DETAIL_LINKED_GOODS_SLIDER" => "Y",
		"SHOW_TOP_PROJECT_BLOCK" => "N",
		"TOP_GALLERY_PROPERTY_CODE" => "PHOTOS",
		"ADDITIONAL_GALLERY_PROPERTY_CODE" => "GALLEY_BIG",
		"MAIN_GALLERY_PROPERTY_CODE" => "GALLEY_BIG",
		"DETAIL_BLOG_URL" => "catalog_comments",
		"COMMENTS_COUNT" => "5",
		"BLOG_TITLE" => "Комментарии",
		"DETAIL_BLOG_EMAIL_NOTIFY" => "N",
		"USE_SUBSCRIBE_IN_TOP" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_DISCOUNT_TIME" => "Y",
		"SHOW_MEASURE" => "N",
		"TAGS_SECTION_COUNT" => "",
		"DISPLAY_LINKED_PAGER" => "Y",
		"MAX_GALLERY_ITEMS" => "5",
		"SHOW_GALLERY_GOODS" => "Y",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => "RUB",
		"ADD_DETAIL_TO_SLIDER" => "Y",
		"SHOW_ONE_CLICK_BUY" => "Y",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_RATING" => "Y",
		"DISPLAY_WISH_BUTTONS" => "Y",
		"STIKERS_PROP" => "-",
		"SALE_STIKER" => "-",
		"SHOW_SECTIONS_FILTER" => "Y",
		"LINKED_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"SHOW_COUNT_ELEMENTS" => "Y",
		"SECTIONS_TAGS_DEPTH_LEVEL" => "2",
		"ADD_PICT_PROP" => "",
		"IBLOCK_CATALOG_TYPE" => "-",
		"IBLOCK_CATALOG_ID" => "43",
		"PRICE_VAT_INCLUDE" => "Y",
		"MESSAGES_PER_PAGE" => "10",
		"USE_CAPTCHA" => "Y",
		"REVIEW_AJAX_POST" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"FORUM_ID" => "1",
		"URL_TEMPLATES_READ" => "",
		"SHOW_LINK_TO_FORUM" => "Y",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"detail" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
		)
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>