<?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"front_map_offer", 
	array(
		"IBLOCK_TYPE" => 'aspro_max_content',
		"IBLOCK_ID" => '82',
		"NEWS_COUNT" => "999",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"SHOW_DISCOUNT_TIME_EACH_SKU" => "N",
		"FILTER_NAME" => 'offersMapFilter',
		"FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "NAME",
		),
		"PROPERTY_CODE" => array(
			0 => "EMAIL",
			1 => "PHONE",
			2 => "ADDRESS",
			3 => "SCHEDULE",
			4 => "METRO",
			5 => "MAP",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => 'A',
		"CACHE_TIME" => '3600000',
		"CACHE_GROUPS" => 'Y',
		"CACHE_FILTER" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => '',
		"PARENT_SECTION_CODE" => '',
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600",
		"PAGER_SHOW_ALL" => "N",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "front_map3",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_LAST_MODIFIED" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"STRICT_SECTION_CHECK" => "N",
		"TITLE_BLOCK" => '',
		"TITLE_BLOCK_DETAIL_NAME" => '',
		"TITLE_BLOCK_ALL" => '',
		"ALL_URL" => '',
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MAP_TYPE" => "0",
		"MESSAGE_404" => ""
	),
	false
);?>