<?
$PERM["promo"]["2"]="D";
$PERM["promo"]["3"]="D";
$PERM["promo"]["7"]="D";
$PERM["promo"]["8"]="D";
$PERM["promo"]["4"]="D";
$PERM["promo"]["12"]="R";
$PERM["promo"]["11"]="R";
$PERM["promo"]["5"]="D";
$PERM["promo"]["6"]="R";
$PERM["promo"]["10"]="R";
$PERM["cart"]["*"]="R";
?>